// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	UserID    pgtype.UUID
	VideoID   pgtype.UUID
	Name      string
	Type      string
	Height    int32
	Width     int32
	VideoUrl  pgtype.Text
	StreamUrl pgtype.Text
}
