// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	JobID     pgtype.UUID
	VideoID   pgtype.UUID
	Name      string
	Type      string
	Options   []byte
	Status    string
	CreatedAt pgtype.Timestamp
}

type Video struct {
	UserID     pgtype.UUID
	VideoID    pgtype.UUID
	Name       string
	Type       string
	Resolution int32
	VideoUrl   pgtype.Text
	StreamUrl  pgtype.Text
	CreatedAt  pgtype.Timestamp
}
