// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: videos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStreamURL = `-- name: GetStreamURL :one
SELECT stream_url FROM videos WHERE Video_id=$1
`

func (q *Queries) GetStreamURL(ctx context.Context, videoID pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getStreamURL, videoID)
	var stream_url pgtype.Text
	err := row.Scan(&stream_url)
	return stream_url, err
}
