// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: videos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchVideo = `-- name: FetchVideo :one
SELECT Name,Video_url FROM videos WHERE Video_id=$1
`

type FetchVideoRow struct {
	Name     string
	VideoUrl pgtype.Text
}

func (q *Queries) FetchVideo(ctx context.Context, videoID pgtype.UUID) (FetchVideoRow, error) {
	row := q.db.QueryRow(ctx, fetchVideo, videoID)
	var i FetchVideoRow
	err := row.Scan(&i.Name, &i.VideoUrl)
	return i, err
}
