// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Revocation struct {
	Token     []byte
	RevokedAt pgtype.Timestamp
}

type User struct {
	Name      string
	Email     string
	Passwd    []byte
	Username  string
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
}
